'use strict';

const { Op } = require('sequelize');
const { Recommendation } = require('../models');
const { runEngine } = require('../services/recommendationEngine');

/**
 * Returns mock cost data structured like a real cloud billing API.
 * Replace with live Cost Explorer / Azure Cost Management / GCP Billing calls.
 */
const getCosts = (req, res) => {
  const { period = '30d', provider } = req.query;

  const allCosts = {
    aws: [
      { service: 'EC2', amount: 1240.50, currency: 'USD', period },
      { service: 'S3', amount: 320.10, currency: 'USD', period },
      { service: 'RDS', amount: 890.00, currency: 'USD', period },
      { service: 'Lambda', amount: 45.80, currency: 'USD', period },
    ],
    azure: [
      { service: 'Virtual Machines', amount: 980.00, currency: 'USD', period },
      { service: 'Blob Storage', amount: 210.00, currency: 'USD', period },
      { service: 'Azure SQL', amount: 640.00, currency: 'USD', period },
    ],
    gcp: [
      { service: 'Compute Engine', amount: 750.00, currency: 'USD', period },
      { service: 'Cloud Storage', amount: 190.00, currency: 'USD', period },
      { service: 'BigQuery', amount: 420.00, currency: 'USD', period },
    ],
  };

  const data = provider ? { [provider]: allCosts[provider] || [] } : allCosts;

  const totalByProvider = Object.entries(data).map(([p, services]) => ({
    provider: p,
    total: services.reduce((sum, s) => sum + s.amount, 0),
    currency: 'USD',
    services,
  }));

  const grandTotal = totalByProvider.reduce((sum, p) => sum + p.total, 0);

  res.json({
    period,
    grandTotal: { amount: parseFloat(grandTotal.toFixed(2)), currency: 'USD' },
    breakdown: totalByProvider,
  });
};

/**
 * Returns mock resource utilisation metrics.
 */
const getUsage = (req, res) => {
  const { provider, resourceType } = req.query;

  const usage = [
    { resourceId: 'r-001', name: 'prod-web-server', provider: 'aws', resourceType: 'ec2', cpuPercent: 67.4, memoryPercent: 72.1, networkMbps: 145, storagePct: 45 },
    { resourceId: 'r-003', name: 'staging-vm', provider: 'azure', resourceType: 'vm', cpuPercent: 12.0, memoryPercent: 30.5, networkMbps: 20, storagePct: 22 },
    { resourceId: 'r-004', name: 'compute-node-1', provider: 'gcp', resourceType: 'instance', cpuPercent: 88.9, memoryPercent: 91.0, networkMbps: 310, storagePct: 60 },
  ];

  let result = usage;
  if (provider) result = result.filter((u) => u.provider === provider);
  if (resourceType) result = result.filter((u) => u.resourceType === resourceType);

  res.json({ data: result, total: result.length });
};

/**
 * Returns DB-backed cost-saving recommendations generated by the rule engine.
 */
const getRecommendations = async (req, res, next) => {
  try {
    const { status = 'open', provider, severity } = req.query;

    // Refresh open recommendations from the engine on each request
    if (!status || status === 'open') {
      await runEngine();
    }

    const where = {};
    if (status) where.status = status;
    if (provider) where.provider = provider;
    if (severity) where.severity = severity;

    const recommendations = await Recommendation.findAll({
      where,
      order: [
        ['severity', 'ASC'],
        ['estimatedMonthlySavings', 'DESC'],
      ],
    });

    const totalSavings = recommendations.reduce((s, r) => s + (r.estimatedMonthlySavings || 0), 0);

    res.json({
      data: recommendations,
      total: recommendations.length,
      totalEstimatedMonthlySavings: { amount: parseFloat(totalSavings.toFixed(2)), currency: 'USD' },
    });
  } catch (err) {
    next(err);
  }
};

/**
 * Update the status of a recommendation (apply or dismiss).
 * PATCH /api/analytics/recommendations/:id
 * Body: { status: 'applied' | 'dismissed' }
 */
const updateRecommendation = async (req, res, next) => {
  try {
    const rec = await Recommendation.findByPk(req.params.id);
    if (!rec) {
      return res.status(404).json({ error: `Recommendation '${req.params.id}' not found.` });
    }

    const { status } = req.body;
    if (!['open', 'applied', 'dismissed'].includes(status)) {
      return res.status(400).json({ error: 'Status must be one of: open, applied, dismissed.' });
    }

    const now = new Date();
    const updates = { status };
    if (status === 'applied') updates.appliedAt = now;
    if (status === 'dismissed') updates.dismissedAt = now;

    await rec.update(updates);
    res.json(rec);
  } catch (err) {
    next(err);
  }
};

module.exports = { getCosts, getUsage, getRecommendations, updateRecommendation };
