'use strict';

const { Recommendation } = require('../models');
const { buildCostsSnapshot, fetchRealCosts } = require('../services/costService');
const {
  enqueueCostSync,
  enqueueRecommendationRefresh,
  getAnalyticsJobStatus,
  getLatestJobResult,
} = require('../queue/analyticsQueue');
const { JOB_NAMES } = require('../queue/jobNames');

/**
 * Returns mock cost data structured like a real cloud billing API.
 * Replace with live Cost Explorer / Azure Cost Management / GCP Billing calls.
 */
const getCosts = async (req, res, next) => {
  try {
    const { period = '30d', provider } = req.query;

    const cached = await getLatestJobResult(JOB_NAMES.costSync);
    if (cached) {
      const filtered = buildCostsSnapshot(period, provider);
      const totalsByProvider = new Map((cached.breakdown || []).map((item) => [item.provider, item]));
      const breakdown = filtered.breakdown.map((item) => totalsByProvider.get(item.provider) || item);
      const grandTotal = breakdown.reduce((sum, item) => sum + item.total, 0);

      return res.json({
        period,
        grandTotal: { amount: parseFloat(grandTotal.toFixed(2)), currency: 'USD' },
        breakdown,
        source: 'queued-cache',
        refreshedAt: cached.refreshedAt || null,
      });
    }

    const snapshot = await fetchRealCosts(period, provider);
    res.json({ ...snapshot, source: snapshot.breakdown.some((b) => b.source === 'live') ? 'live' : 'fallback-mock' });
  } catch (err) {
    next(err);
  }
};

/**
 * Returns mock resource utilisation metrics.
 */
const getUsage = (req, res) => {
  const { provider, resourceType } = req.query;

  const usage = [
    { resourceId: 'r-001', name: 'prod-web-server', provider: 'aws', resourceType: 'ec2', cpuPercent: 67.4, memoryPercent: 72.1, networkMbps: 145, storagePct: 45 },
    { resourceId: 'r-003', name: 'staging-vm', provider: 'azure', resourceType: 'vm', cpuPercent: 12.0, memoryPercent: 30.5, networkMbps: 20, storagePct: 22 },
    { resourceId: 'r-004', name: 'compute-node-1', provider: 'gcp', resourceType: 'instance', cpuPercent: 88.9, memoryPercent: 91.0, networkMbps: 310, storagePct: 60 },
  ];

  let result = usage;
  if (provider) result = result.filter((u) => u.provider === provider);
  if (resourceType) result = result.filter((u) => u.resourceType === resourceType);

  res.json({ data: result, total: result.length });
};

/**
 * Returns DB-backed cost-saving recommendations generated by the rule engine.
 */
const getRecommendations = async (req, res, next) => {
  try {
    const { status = 'open', provider, severity } = req.query;

    const where = {};
    if (status) where.status = status;
    if (provider) where.provider = provider;
    if (severity) where.severity = severity;

    const recommendations = await Recommendation.findAll({
      where,
      order: [
        ['severity', 'ASC'],
        ['estimatedMonthlySavings', 'DESC'],
      ],
    });

    const totalSavings = recommendations.reduce((s, r) => s + (r.estimatedMonthlySavings || 0), 0);

    res.json({
      data: recommendations,
      total: recommendations.length,
      totalEstimatedMonthlySavings: { amount: parseFloat(totalSavings.toFixed(2)), currency: 'USD' },
    });
  } catch (err) {
    next(err);
  }
};

const queueRecommendationRefresh = async (req, res, next) => {
  try {
    const job = await enqueueRecommendationRefresh({
      userId: req.user.sub,
      email: req.user.email,
      role: req.user.role,
    });

    res.status(202).json({
      message: 'Recommendation refresh queued.',
      job,
    });
  } catch (err) {
    next(err);
  }
};

const queueCostSync = async (req, res, next) => {
  try {
    const job = await enqueueCostSync({
      userId: req.user.sub,
      email: req.user.email,
      role: req.user.role,
    });

    res.status(202).json({
      message: 'Cost sync queued.',
      job,
    });
  } catch (err) {
    next(err);
  }
};

const getAnalyticsJob = async (req, res, next) => {
  try {
    const job = await getAnalyticsJobStatus(req.params.jobId);
    if (!job) {
      return res.status(404).json({ error: `Job '${req.params.jobId}' not found.` });
    }

    res.json(job);
  } catch (err) {
    next(err);
  }
};

/**
 * Update the status of a recommendation (apply or dismiss).
 * PATCH /api/analytics/recommendations/:id
 * Body: { status: 'applied' | 'dismissed' }
 */
const updateRecommendation = async (req, res, next) => {
  try {
    const rec = await Recommendation.findByPk(req.params.id);
    if (!rec) {
      return res.status(404).json({ error: `Recommendation '${req.params.id}' not found.` });
    }

    const { status } = req.body;
    if (!['open', 'applied', 'dismissed'].includes(status)) {
      return res.status(400).json({ error: 'Status must be one of: open, applied, dismissed.' });
    }

    const now = new Date();
    const updates = { status };
    if (status === 'applied') updates.appliedAt = now;
    if (status === 'dismissed') updates.dismissedAt = now;

    await rec.update(updates);
    res.json(rec);
  } catch (err) {
    next(err);
  }
};

module.exports = {
  getCosts,
  getUsage,
  getRecommendations,
  queueCostSync,
  queueRecommendationRefresh,
  getAnalyticsJob,
  updateRecommendation,
};
